### ISSUE TITLE
Profile post feed doesn't load

### ISSUE THREAD

**Issue by Fermain** [richiebotteri/meetzy#46]
When visiting my profile, the post feed does not load. The API request is a success, but nothing is rendered.

**Comment by richiebotteri** [comment]
Again, i'm not sure you have the correct version of the project. I have downloaded the JS2 repo, npm installed the dependencies and i can see the post-feed. No issues. Other students have confirmed this as well

**Comment by richiebotteri** [comment]
The problem should be fixed now. this is also related to that one if statement variable not being lowercase
