### ISSUE TITLE
Cannot edit or delete my posts

### ISSUE THREAD

**Issue by Fermain** [richiebotteri/meetzy#48]
I am unable to see the UI needed to update or delete a post.

**Comment by richiebotteri** [comment]
I just downloaded the whole JS2 project file and installed all the dependencies. Everything works. I can see the filter menu button with edit and delete. other students have confirmed this as well before submission. What project-folder are you downloading? the pull-request itself is older and site has been updated since than. I havent closed it since i had an understanding that it has been updated as well?

**Comment by Fermain** [comment]
It will be updated with any new changes added to `js2` branch. Is there another branch I should be checking?

**Comment by richiebotteri** [comment]
The JS2 branch is the one i have downloaded and tested. What browser are you using? Not that i think thats the issue here but worth checking out

**Comment by Fermain** [comment]
Please see screenshots from a fresh test run. I removed all of your files and used GH desktop to clone the PR.

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/10801540/208235348-935a7d72-b870-42ab-97d7-1017593cd183.png">

I then ran `npm i` and `npm start` to run the application:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10801540/208235397-170bb78b-10ea-4cbd-af80-a82ab9d2b47f.png">

I then navigate to `Home` to find one of my test posts:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/10801540/208235408-a027cc42-ccbe-4a3b-8873-4f3ebf27cee3.png">

I then click into it to view the post on it's own:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/10801540/208235425-90761bae-7830-4d15-8996-8cd319b7e75b.png">

**Comment by richiebotteri** [comment]
All fixed now. This issue was caused by me not converting a variable to lowercase. this was fixed but somehow it didnt get uploaded to the js2 repo.

**Comment by Fermain** [comment]
I have tested this and it is working well.
